### PR TITLE
[FSD-768] Docs for Devices

### PR DESCRIPTION
**Pull request by acdameli**

### CODE REVIEW

**Comment by stagebloc-iceman** [comment]
This is going to be a minor pain for conflicts with #50, alas. If we could guarantee that was going out very soon, this week or first thing next week, I'd suggest branching these changes off of that one instead but since that one seems on indefinite hiatus ... :man_shrugging: I suppose that's why you put it at the bottom of the documentation instead of next to or inside of Auth? :)

**Comment by stagebloc-iceman** [comment]
@acdameli Could you revisit this to handle any merge conflicts, adjust the headers to match the new format, etc so we can get it moving again?

**Comment by acdameli** [comment]
@stagebloc-iceman that look right to you now? I can finally remove the extra whitespace at the end of lines that for some formatting reason was previously needed? Hallelujah. 🙏

**Comment by stagebloc-iceman** [comment]
@acdameli Yep. Just one small tweak and these changes are good to go.

The whitespace on the definition JSON is off so it's not getting quoting.

selection_001_2017-05-18

FWIW You can copy this file into `core/docs/` and the development box will use it for preview purposes.
```bash
/home/localhost/core $ cp ../docs/api_v1.md docs/
```

**Pull request merged**
